version: '1'
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5434:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env.dev
    environment:
      RAILS_ENV: $RAILS_ENV
      DB_HOST: $DB_HOST_NAME
      DB_NAME: $DB_NAME
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
networks:
  default:
    name: blog_network
