name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update container on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_HOST}}
        key: ${{secrets.SERVER_SSH_KEY}}
        username: ${{secrets.SERVER_USERNAME}}
        script: |
          ls -la
          cd blog-backend
          git pull
          sudo docker compose --env-file .env.prod -f prod.docker-compose.yml build
          sudo docker compose --env-file .env.prod -f prod.docker-compose.yml up -d --force-recreate backend
          echo "finish"
